# Our base image is Ruby 2.3
FROM ruby:2.3

# Create user and group
RUN groupadd web --gid 6156 \
    && useradd --home /home/web --create-home --shell /bin/false --uid 6157 --gid 6156 web

# Run as web user from here on
USER web

ENV APP_HOME=/home/web/app \
    DEBIAN_FRONTEND=noninteractive \
    DEBIAN_PRIORITY=critical \
    DEBCONF_NOWARNINGS=yes

# Import ENV needed for build process
ARG RAILS_ENV
ARG SECRET_KEY_BASE
ARG DATABASE_URL

# Setup app home
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# Copy files to app home
COPY . $APP_HOME

# Install build essentials
RUN apt-get update -qq && apt-get install -y \
    build-essential \
  # Delete apt caches
  && rm -rf /var/lib/apt/lists/*

# Add NodeJS deb source repository
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
    imagemagick \
    nodejs \
  && rm -rf /var/lib/apt/lists/*

# Build process
RUN \
  # Install gulp globally
  npm install --production --global gulp \
  # Install NPM packages
  && npm install --production \
  # Compile our assets
  && RAILS_ENV=$RAILS_ENV gulp build \
  # Disable bundler from installing documentation
  && echo 'gem: --no-rdoc --no-ri' >> /.gemrc \
  && echo 'gem: --no-document' >> ~/.gemrc \
  # Install application gems.
  && bundle install --no-cache --clean --jobs 10 --retry 5 --without development test --with production \
  # Precompile Rails assets.
  && RAILS_ENV=$RAILS_ENV SECRET_KEY_BASE=$SECRET_KEY_BASE DATABASE_URL=$DATABASE_URL bundle exec rake assets:precompile \
  # Clean caches
  && npm cache clean

# Run your application with Puma.
CMD bundle exec puma -C config/puma.rb
