# Our base image is Ruby 2.3, running on Alpine Linux.
FROM ruby:2.3-alpine

# Import ENV needed for build process
ARG RAILS_ENV
ARG SECRET_KEY_BASE
ARG DATABASE_URL

# Build packages are system packages that are only required for installing
# gems, precompiling assets, etc. They are not included in the final Docker
# image.
ENV BUILD_PACKAGES \
    postgresql-dev

# Runtime packages are system packages that are required for the application
# to run. They are included in the final Docker image.
ENV RUNTIME_PACKAGES \
    postgresql-libs

# Set Rails environment to production
ENV RAILS_ENV production
ENV RACK_ENV production

# Copy your application into the container.
COPY . .

# Build your application.
RUN \
    # Upgrade old packages.
    apk --update upgrade && \
    # Ensure we have ca-certs installed.
    apk add --no-cache ca-certificates && \
    # Install build packages.
    apk add --virtual build-packages build-base $BUILD_PACKAGES && \
    # Install runtime packages.
    apk add --virtual runtime-packages nodejs tzdata $RUNTIME_PACKAGES && \
    # Install Gulp globally
    npm install --production --global gulp && \
    # Install NPM packages
    npm install --production && \
    # Compile our assets
    RAILS_ENV=$RAILS_ENV gulp build && \
    # Install application gems.
    bundle install --jobs 10 --retry 5 --without development test --with production && \
    # Precompile Rails assets.
    RAILS_ENV=$RAILS_ENV SECRET_KEY_BASE=$SECRET_KEY_BASE DATABASE_URL=$DATABASE_URL bundle exec rake assets:precompile && \
    # Clean up build packages.
    apk del --purge build-packages && \
    # Delete APK and gem caches.
    find / -type f -iname \*.apk-new -delete && \
    rm -rf /var/cache/apk/* && \
    rm -rf /usr/local/lib/ruby/gems/*/cache/* && \
    rm -rf ~/.gem

# TODO:
# - Clean up NPM packages
# - See if we can tweak NPM install for production

# Run your application with Puma.
CMD bundle exec puma -C config/puma.rb
