# TODO:
# - Create user and group (https://github.com/rdsubhas/ruby-deploy-kickstart/blob/master/Dockerfile)
# - /etc/gemrc:
#   gem: --no-ri --no-rdoc
# - bundle install --deployment --clean --without development test

# Our base image is Ruby 2.3
FROM ruby:2.3

ENV APP_HOME=/app \
    DEBIAN_FRONTEND=noninteractive \
    DEBIAN_PRIORITY=critical \
    DEBCONF_NOWARNINGS=yes

# Import ENV needed for build process
ARG RAILS_ENV
ARG SECRET_KEY_BASE
ARG DATABASE_URL

# Install build essentials
RUN apt-get update -qq && apt-get install -y \
    build-essential \
  # Delete apt caches
  && rm -rf /var/lib/apt/lists/*

# Add NodeJS deb source repository
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
    imagemagick \
    nodejs \
  && rm -rf /var/lib/apt/lists/*

# Copy app into container
COPY . .

# Build process
RUN \
  # Install gulp globally
  npm install --production --global gulp \
  # Install NPM packages
  && npm install --production \
  # Compile our assets
  && RAILS_ENV=$RAILS_ENV gulp build \
  # Disable bundler from installing documentation
  && echo 'gem: --no-rdoc --no-ri' >> /.gemrc \
  && echo 'gem: --no-document' >> ~/.gemrc \
  # Install application gems.
  && bundle install --jobs 10 --retry 5 --without development test --with production \
  # Precompile Rails assets.
  && RAILS_ENV=$RAILS_ENV SECRET_KEY_BASE=$SECRET_KEY_BASE DATABASE_URL=$DATABASE_URL bundle exec rake assets:precompile \
  # Clean caches
  && npm cache clean \
  && rm -rf /usr/local/lib/ruby/gems/*/cache/* \
  && rm -rf ~/.gem \

# Run your application with Puma.
CMD bundle exec puma -C config/puma.rb
