default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
